# Generated by Django 5.2 on 2025-04-20 23:54

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTagEdifici',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=1000)),
                ('icon', models.URLField(blank=True)),
                ('author', models.ForeignKey(default=posts.models.get_anonymus_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('edificis', models.ManyToManyField(to='posts.subtagedifici')),
                ('tags', models.ManyToManyField(to='posts.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagSeccio',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.tag')),
                ('edificis', models.ManyToManyField(to='posts.subtagedifici')),
            ],
            bases=('posts.tag',),
        ),
    ]
