# Generated by Django 5.1.5 on 2025-04-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagBuilding',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.tag')),
                ('icon', models.URLField(blank=True)),
            ],
            bases=('posts.tag',),
        ),
    ]
