# Generated by Django 5.1.7 on 2025-06-26 15:45

import django.db.models.deletion
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_creationd_post_lastmodif'),
        ('postsauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=posts.models.get_anonymus_user, on_delete=django.db.models.deletion.CASCADE, to='postsauth.distritolibreuser'),
        ),
    ]
