# Generated by Django 5.1.5 on 2025-04-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tagbuilding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
