# Generated by Django 5.1.5 on 2025-04-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagbuilding',
            name='icon',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
