# Generated by Django 5.1.5 on 2025-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('ANARQUISMOCRISTIANO', 'Anarquismocristiano'), ('COMUNALISMOTRADICIONALISTA', 'Comunalismotradicionalista'), ('PAELOLIBERTARISMO', 'Paelolibertarismo'), ('SOCIALISMOCRISTIANO', 'Socialismocristiano'), ('LIBERALISMOCONSERVADOR', 'Liberalismoconservador'), ('NACIONALBOLCHEVISMO', 'Nacionalbolchevismo'), ('FASCISMOCLERICAL', 'Fascismoclerical'), ('NEOREACCIONNRX', 'Neoreaccionnrx'), ('ANARCOCOMUNISMO', 'Anarcocomunismo'), ('MUTUALISMO', 'Mutualismo'), ('LIBERTARISMO', 'Libertarismo'), ('SOCIALISMODEMOCRATICO', 'Socialismodemocratico'), ('LIBERALISMOCLASICO', 'Liberalismoclasico'), ('MARXISMOLENINISMO', 'Marxismoleninismo'), ('FASCISMOCLASICO', 'Fascismoclasico'), ('CAPITALISMOILIBERAL', 'Capitalismoiliberal'), ('POSANARQUISMO', 'Posanarquismo'), ('ANARQUISMOEGOISTA', 'Anarquismoegoista'), ('IZQUIERDALIBERTARIA', 'Izquierdalibertaria'), ('LUXEMBURGISMO', 'Luxemburgismo'), ('COMUNISMOPOSMARXISTA', 'Comunismoposmarxista'), ('SOCIOLIBERALISMO', 'Socioliberalismo'), ('TECNOCRACIAPROGRESISTA', 'Tecnocraciaprogresista'), ('JACOBINISMO', 'Jacobinismo'), ('NOSECTION', 'Nosection')], default='NOSECTION', max_length=50),
        ),
    ]
