# Generated by Django 5.1.7 on 2025-04-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTagEdifici',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='coverimg',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='edificis',
            field=models.ManyToManyField(to='posts.subtagedifici'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='posts.tag'),
        ),
    ]
