# Generated by Django 5.1.7 on 2025-04-19 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_subtagedifici_tag_rename_coverimg_post_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSeccio',
            fields=[
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.tag')),
            ],
        ),
    ]
