# Generated by Django 5.1.7 on 2025-04-19 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_tagseccio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagseccio',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='posts.tag'),
        ),
    ]
