# Generated by Django 5.1.7 on 2025-04-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_tagseccio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagseccio',
            name='edificis',
            field=models.ManyToManyField(to='posts.subtagedifici'),
        ),
    ]
