# Generated by Django 5.1.1 on 2024-09-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('logo', models.URLField()),
                ('author', models.CharField(max_length=30)),
                ('title_art', models.CharField(max_length=60)),
                ('author_art', models.CharField(max_length=30)),
                ('resum_art', models.CharField(max_length=200)),
            ],
        ),
    ]
