# Generated by Django 5.1.1 on 2024-09-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguteca', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='resum_art',
            new_name='summary_art',
        ),
    ]
