# Generated by Django 5.1.1 on 2024-09-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguteca', '0003_rename_resum_art_post_summary_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.CharField(max_length=200),
        ),
    ]
