from django.db import models
from django.contrib.auth.models import User

# Create your models here.


def get_anonymus_author():
    return User.objects.get_or_create(username="anonymus")[0].id


class Post(models.Model):
    ANARQUISMOCRISTIANO = "ANARQUISMOCRISTIANO"
    COMUNALISMOTRADICIONALISTA = "COMUNALISMOTRADICIONALISTA"
    PAELOLIBERTARISMO = "PAELOLIBERTARISMO"
    SOCIALISMOCRISTIANO = "SOCIALISMOCRISTIANO"
    LIBERALISMOCONSERVADOR = "LIBERALISMOCONSERVADOR"
    NACIONALBOLCHEVISMO = "NACIONALBOLCHEVISMO"
    FASCISMOCLERICAL = "FASCISMOCLERICAL"
    NEOREACCIONNRX = "NEOREACCIONNRX"
    ANARCOCOMUNISMO = "ANARCOCOMUNISMO"
    MUTUALISMO = "MUTUALISMO"
    LIBERTARISMO = "LIBERTARISMO"
    SOCIALISMODEMOCRATICO = "SOCIALISMODEMOCRATICO"
    LIBERALISMOCLASICO = "LIBERALISMOCLASICO"
    MARXISMOLENINISMO = "MARXISMOLENINISMO"
    FASCISMOCLASICO = "FASCISMOCLASICO"
    CAPITALISMOILIBERAL = "CAPITALISMOILIBERAL"
    POSANARQUISMO = "POSANARQUISMO"
    ANARQUISMOEGOISTA = "ANARQUISMOEGOISTA"
    IZQUIERDALIBERTARIA = "IZQUIERDALIBERTARIA"
    LUXEMBURGISMO = "LUXEMBURGISMO"
    COMUNISMOPOSMARXISTA = "COMUNISMOPOSMARXISTA"
    SOCIOLIBERALISMO = "SOCIOLIBERALISMO"
    TECNOCRACIAPROGRESISTA = "TECNOCRACIAPROGRESISTA"
    JACOBINISMO = "JACOBINISMO"
    NOSECTION = "NOSECTION"
    SECTIONS = {
        ANARQUISMOCRISTIANO: "ANARQUISMOCRISTIANO",
        COMUNALISMOTRADICIONALISTA: "COMUNALISMOTRADICIONALISTA",
        PAELOLIBERTARISMO: "PAELOLIBERTARISMO",
        SOCIALISMOCRISTIANO: "SOCIALISMOCRISTIANO",
        LIBERALISMOCONSERVADOR: "LIBERALISMOCONSERVADOR",
        NACIONALBOLCHEVISMO: "NACIONALBOLCHEVISMO",
        FASCISMOCLERICAL: "FASCISMOCLERICAL",
        NEOREACCIONNRX: "NEOREACCIONNRX",
        ANARCOCOMUNISMO: "ANARCOCOMUNISMO",
        MUTUALISMO: "MUTUALISMO",
        LIBERTARISMO: "LIBERTARISMO",
        SOCIALISMODEMOCRATICO: "SOCIALISMODEMOCRATICO",
        LIBERALISMOCLASICO: "LIBERALISMOCLASICO",
        MARXISMOLENINISMO: "MARXISMOLENINISMO",
        FASCISMOCLASICO: "FASCISMOCLASICO",
        CAPITALISMOILIBERAL: "CAPITALISMOILIBERAL",
        POSANARQUISMO: "POSANARQUISMO",
        ANARQUISMOEGOISTA: "ANARQUISMOEGOISTA",
        IZQUIERDALIBERTARIA: "IZQUIERDALIBERTARIA",
        LUXEMBURGISMO: "LUXEMBURGISMO",
        COMUNISMOPOSMARXISTA: "COMUNISMOPOSMARXISTA",
        SOCIOLIBERALISMO: "SOCIOLIBERALISMO",
        TECNOCRACIAPROGRESISTA: "TECNOCRACIAPROGRESISTA",
        JACOBINISMO: "JACOBINISMO",
        NOSECTION: "NOSECTION",
    }

    title = models.CharField(max_length=50)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, default=get_anonymus_author
    )
    section = models.CharField(max_length=50, choices=SECTIONS, default=NOSECTION)
    content = models.CharField(max_length=1000, blank=True)
    coverimg = models.URLField(blank=True)
